#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

run_code_quality_checks() {
  bundle exec rubocop .
}

run_unit_tests() {
  bundle exec rake spec:coverage
}

run_integration_tests() {
  local pwd=$PWD
  local root="$pwd/spec/integration"

  for test in $(find $root -name '*_spec.rb')
  do
    run_integration_test $test

    if [ $? -ne 0 ]; then
      local exit_code=$?
      echo "Failing test: $test"
      exit $exit_code
    fi
  done
}

run_integration_test() {
  local test=$1

  printf "\n\n\nRunning: $test\n"
  bundle exec rspec $test
}

run_test() {
  local test=$1

  printf "\n\n\nRunning: $test\n"
  COVERAGE=true bundle exec rspec $test
}

main() {
  run_code_quality_checks &&
    run_unit_tests &&
    run_integration_tests
}

main
